appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: Ruprym0mjRvnaEWqbz+emaOQAuST16e8/33FAiuZPv5eMWIorQJKiIyKF1NmD6orYf6eSRonKLLZ36FfMR97jYAJB0nR7Cj44r9acl0rYUXshZ6jc2OIt2SjX1W5NDGObOE6mPQQoyhJlZ0VxF7eRFcV2H5Is7kzp1QwIa+1D9SsMdYHJkZ/r0Fe5NK/kJ+QYOlAkdvObMVtvraUQPp1/3DfMSf4Mj9l81zKISusMFFsvqSETre1OcY1AF6hAWw6vy05eXrb3zvodk0ReFoi2oIPH60GolnhBhdIzoGRuBqQUa0g83RL7L3Ks1qmQREkf3uILpvaE3wLBxXFEV3HjEMCNfkMXSk/fqqWRbR1OJJieuQNAbe1PmVlYTzgXdPp4Zoqo+XD7pZDJOJM5cJM9rweIMejPdMOeDehTMOjlhrcPA7Xj+fH95RsEMZJ5j+kmdXeZu7wC9KeBfWYVnWG6cFuzsHtfyzsBF05gNXSxMppmsH7wwO4Zx5+aiZLuDqISLGlTI4Yz30LUZ0tHfH2hKVEaVIzHZfe8PNOmsgXk7Le8xKrFvQN6JCHEx5o4x7YZDscZZdJxlSQjCk878BNZq+XcwqCpEb+85GvFq1kFLFnJ1lC/kDdubbs7kc7hxYwPPiJz2T1GQynA75HBZHb5AP/l+yACldxmF0RckjCEHw=}
